apple/pir-service-example

Package.resolved
Package.swift

Bump swift-homomophic-encryption version to get https://github.com/apple/swift-homomorphic-encryption/pull/9; this should fix swift package index [build failures](https://swiftpackageindex.com/builds/4CB3529D-1C52-4BC2-8579-AE4F1F0F4782):
```
fatal: clone of 'git@github.com:apple/swift-homomorphic-encryption-protobuf.git' into submodule path '/host/spi-builder-workspace/.build/checkouts/swift-homomorphic-encryption/swift-homomorphic-encryption-protobuf' failed
```

Bump swift-homomorphic-encryption version

---

Sources/PIRService/Extensions/HEError+HTTPErrorResponse.swift
Sources/PIRService/Extensions/PrivacyPass+ResponseGenerator.swift
Sources/PIRService/server.swift

Swift 5.10 compiler does not know about `@retroactive` attribute.

Remove @retroactive

---

README.md

Otherwise people might miss the documentation hosted there.

Provide a link to Swift Package Index explicitly.

---

README.md

Swift Package Index does not rewrite the relative path for the dark mode image.
This should help.

Use absolute path to images in README

---

Package.resolved
Package.swift
Sources/PIRService/Controllers/PIRServiceController.swift
Tests/PIRServiceTests/PIRServiceControllerTests.swift
Tests/PIRServiceTests/TestClientProtocol+Protobuf.swift

Only the config fetch should use Response compression.
Other endpoints (key upload & query) handle ciphertexts that are hard to compress.

Add response compression for Config fetch endpoint

---

Sources/PIRService/Controllers/PrivacyPassController.swift
Sources/PIRService/Controllers/PrivacyPassState.swift
Sources/PIRService/PIRService.docc/TestingInstructions.md
Sources/PIRService/server.swift

Hopefully now there are no more users on iOS 18 early betas, that needed the full URL in the token issuer directory configuration.

Remove issuerRequestUri from configuration

---

Sources/PIRService/Controllers/PrivacyPassController.swift
Sources/PIRService/Extensions/PrivacyPass+ResponseGenerator.swift
Sources/PrivacyPass/Issuer.swift
Sources/PrivacyPass/PrivacyPassError.swift
Sources/PrivacyPass/PublicKey.swift
Sources/PrivacyPass/Token.swift
Sources/PrivacyPass/TokenRequest.swift
Sources/PrivacyPass/TokenResponse.swift

Adding a case to a public enum is a source-breaking change.
To avoid this, (especially since we aren't yet at 1.0.0), we refactor the error type to hide the underlying enum.

Make PrivacyPassError a struct for better backwards-compatibility.

---

Package.resolved
Package.swift
Sources/PIRService/Controllers/PrivacyPassController.swift
Sources/PIRServiceTesting/PIRClient+KeyRotation.swift
Sources/PIRServiceTesting/PIRClient+PrivacyPass.swift
Sources/PIRServiceTesting/PIRClient.swift
Sources/PIRServiceTesting/PIRClientError.swift
Sources/PIRServiceTesting/PIRConfig+ShardConfig.swift
Sources/PIRServiceTesting/TestClientProtocol+Protobuf.swift
Tests/PIRServiceTests/ExampleUsecase.swift
Tests/PIRServiceTests/PIRServiceControllerTests.swift
Tests/PIRServiceTests/PIRServiceTests.swift
Tests/PIRServiceTests/TestClientProtocol+Protobuf.swift

Simplifies writing unit tests by introducing a new library that implements the client side.

Implement client side for testing

---

Package.resolved
Package.swift
Sources/PIRService/Application+build.swift
Sources/PIRService/Controllers/PIRServiceController.swift
Sources/PIRService/Controllers/PirUsecase.swift
Sources/PIRService/Controllers/UsecaseStore.swift
Sources/PIRService/Middlewares/LogErrorsMiddleware.swift
Sources/PIRService/ReloadService.swift
Sources/PIRService/server.swift
Tests/PIRServiceTests/ExampleUsecase.swift
Tests/PIRServiceTests/PIRServiceControllerTests.swift
Tests/PIRServiceTests/PIRServiceTests.swift

This implements two things:
* Supporting multiple versions of a dataset & routing to the right dataset based on configuration identifier.
* Reloading of the configuration when SIGHUP signal is sent to the process.

Reload configuration & usecases on SIGHUP

---

Package.swift
Sources/PIRService/Application+build.swift
Sources/PIRService/Controllers/PIRServiceController.swift
Sources/PIRService/Controllers/PirUsecase.swift
Sources/PIRService/Controllers/Usecase.swift
Sources/PIRService/Extensions/PirConfig+compatible.swift
Sources/PIRService/Middlewares/ExtractPlatform.swift
Sources/PIRService/PIRService.docc/HTTPEndpoints.md
Sources/PIRService/PIRService.docc/TestingInstructions.md
Sources/PIRServiceTesting/PIRClient.swift
Sources/PIRServiceTesting/PIRConfig+ShardConfig.swift
Sources/Util/OperatingSystem.swift
Sources/Util/Platform.swift
Tests/PIRServiceTests/ExampleUsecase.swift
Tests/PIRServiceTests/PIRServiceTests.swift
Tests/PIRServiceTests/TestClientProtocol+Protobuf.swift
Tests/UtilTests/UtilTests.swift

As of iOS 18.2 (beta 2), when all shard configurations are identical, `PIR Fixed Shard Config` allows for a more compact PIR config, saving bandwidth and client-side memory usage. To enable, set the `pirShardConfigs` field in the PIR config. iOS clients prior to iOS 18.2 will still require the `shardConfigs` field to be set. See [Reusing PIR Parameters]( https://swiftpackageindex.com/apple/swift-homomorphic-encryption/main/documentation/privateinformationretrieval/reusingpirparameters) for how to process the database such that all shard configurations are identical.

Add Fixed PIR Shard Config

---

Sources/PIRService/Controllers/PIRServiceController.swift
Sources/PIRService/Controllers/Usecase.swift
Sources/PIRService/PIRService.docc/HTTPEndpoints.md
Sources/PIRService/PIRService.docc/TestingInstructions.md
Tests/PIRServiceTests/PIRServiceControllerTests.swift

Add support for reusing  existingConfigId
As of iOS 18.2 (seed 2), during the `config` request, if a client has a cached configuration, it will send the config id of that cached configuration. Then, if the configuration is unchanged, the server may respond with a config setting `reuseExistingConfig = true` and omit any other fields. This helps reduce the response size for the config fetch.

Add support for reusing existingConfigId

---

Sources/PIRService/Controllers/PIRServiceController.swift
Sources/PIRService/Extensions/PirConfig+compatible.swift
Sources/PIRService/PIRService.docc/TestingInstructions.md
Tests/PIRServiceTests/PIRServiceControllerTests.swift
Tests/PIRServiceTests/PIRServiceTests.swift

Configuring sharding function is not backwards compatible.

Throw error when incompatible platform is used

---

Sources/PIRService/Middlewares/UserTierAuthentication.swift

fix https://github.com/apple/live-caller-id-lookup-example/issues/57

Added String type to UserTier enum.

---

.github/workflows/ci.yaml
.gitignore
.pre-commit-config.yaml

* Fix CI for copyright header (similar to https://github.com/apple/swift-homomorphic-encryption/pull/139)
* Pin CI to Ubuntu 22.04 (similar to https://github.com/apple/swift-homomorphic-encryption/pull/145)
* Update pre-commit deps

Fix CI for copyright header

---

README.md

As noted at https://github.com/apple/swift-homomorphic-encryption/tree/b73daaca802e16c9f6a31da76f26375c34896c15?tab=readme-ov-file#swift--xcode-versions, swift-homomorphic-encryption requires XCode >= 16.1
Related to https://github.com/apple/live-caller-id-lookup-example/issues/62

Add Xcode 16.1 dependency (#70)

---

.github/workflows/ci.yaml

Don't run CI on ready_for_review, since it already runs on every push.

Don't run CI on ready_for_review

---

Package.resolved
Sources/PIRService/Extensions/ProtobufExtensions.swift
Sources/PIRService/main.swift
Sources/PIRServiceTesting/PIRClient+PrivacyPass.swift
Tests/PIRServiceTests/TestClientProtocol+Protobuf.swift

Similar to https://github.com/apple/swift-homomorphic-encryption/pull/193, this avoids a bug where running unit-tests in release mode didn't work, for a test target that depends on an executable target.
Newer swift-nio is needed to prevent unit-tests from hanging, so we update dependencies.

Fix release unit-tests, by avoiding using @main

---

.github/workflows/ci.yaml
.license_header_template
.licenseignore
.pre-commit-config.yaml
.spi.yml
.swiftformat
.swiftlint.yml
.yamllint.yml
Sources/PIRService/Controllers/Usecase.swift
Sources/PIRService/Controllers/UserAuthenticator.swift
Sources/PIRService/PIRService.docc/Authentication.md
Sources/PIRService/PIRService.docc/CommonErrors.md
Sources/PIRService/PIRService.docc/Onboarding.md
Sources/PIRService/PIRService.docc/TestingInstructions.md
Sources/PrivacyPass/PublicKey+request.swift
ci/install-lockwood-swiftformat.sh
ci/install-swiftlint.sh

Adopt [github-workflows](https://github.com/swiftlang/github-workflows/tree/main), including:
* updating swiftformat / swiftlint versions
* running CI on release branches
* remove copyright header from yaml files (since github-workflows doesn't require it)
* switch SwiftLint CI to debug mode, since building in release mode is slow

Adopt GitHub workflows

---

Sources/PIRService/ReloadService.swift

The message was: "User token '	oken' is assigned to multiple tiers 'tier1' and 'tier2', using the latter."
This is because of missing parentheses.

Fix token assigned to multiple tiers error message

---

Sources/PIRService/Controllers/PIRServiceController.swift
Tests/PIRServiceTests/PIRServiceControllerTests.swift

Currently, when a usecase is not found on the server we get a error message like this:
```
Invalid existingConfigIds count 1. Expected 0 or 0.
```
This PR adds a nicer error message:
```
One or more usecases not found. Requested usecases: ["other"].
Usecases available on the server: ["test"].
```

Improve unknown usecase error message
